title: Yau Group Handbook
description: Help and information about the group 
remote_theme: pages-themes/minimal@v0.2.0
markdown: kramdown
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
